/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fine_ndksample_ndkInterface_HttpUtil */

#ifndef _Included_com_example_fine_ndksample_ndkInterface_HttpUtil
#define _Included_com_example_fine_ndksample_ndkInterface_HttpUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fine_ndksample_ndkInterface_HttpUtil
 * Method:    doPostRequest
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fine_ndksample_ndkInterface_HttpUtil_doPostRequest
  (JNIEnv *, jclass, jstring, jint, jstring, jstring);

/*
 * Class:     com_example_fine_ndksample_ndkInterface_HttpUtil
 * Method:    doGetRequest
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fine_ndksample_ndkInterface_HttpUtil_doGetRequest
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_example_fine_ndksample_ndkInterface_HttpUtil
 * Method:    doSocketConnect
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fine_ndksample_ndkInterface_HttpUtil_doSocketConnect
  (JNIEnv *, jclass, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
