/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fine_ndksample_SystemProperties */

#ifndef _Included_com_example_fine_ndksample_SystemProperties
#define _Included_com_example_fine_ndksample_SystemProperties
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fine_ndksample_SystemProperties
 * Method:    native_get
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fine_ndksample_SystemProperties_native_1get
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
